services:
  postgres:
    image: postgres:16

    container_name: pmo-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: pmo_user
      POSTGRES_PASSWORD: pmo_password
      POSTGRES_DB: pmo_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: