"""create project artifacts table

Revision ID: 4aa3aaca98db
Revises: 651ab3fb7177
Create Date: 2026-08-05 13:35:09.618521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa3aaca98db'
down_revision: Union[str, Sequence[str], None] = '651ab3fb7177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_artifacts_document_analysis_id'), 'project_artifacts', ['document_analysis_id'], unique=False)
    op.create_index(op.f('ix_project_artifacts_id'), 'project_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_project_artifacts_project_id'), 'project_artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_artifacts_project_id'), table_name='project_artifacts')
    op.drop_index(op.f('ix_project_artifacts_id'), table_name='project_artifacts')
    op.drop_index(op.f('ix_project_artifacts_document_analysis_id'), table_name='project_artifacts')
    op.drop_table('project_artifacts')
    # ### end Alembic commands ###
