"""create document analyses table

Revision ID: 651ab3fb7177
Revises: 98f0e1d19406
Create Date: 2026-08-05 00:17:02.286082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651ab3fb7177'
down_revision: Union[str, Sequence[str], None] = '98f0e1d19406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_id'), 'document_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_analyses_id'), table_name='document_analyses')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
